from time import sleep
print('//////'*18)
sleep(1)
print('')
print('                                                CALCULADORA DE IMC')
sleep(1)
print('')
print('//////'*18)
print('')
peso=float(input('            DIGITE SEU PESO (KG): '))
print('')
sleep(1)
altura=float(input('            DIGITE SUA ALTURA: '))
imc=peso/altura**2
print('')
sleep(1)
print("            SEU IMC é: {:.3f}".format(imc))
print('')
print('')
sleep(1)
print('                                            ANALISANDO SEU IMC... ')
sleep(1)
print('')
print('                                                 AGUARDE... ')
print('')
print('')
sleep(2)
if imc<16:
    print('//////'*18)
    print('')
    print('                                           MAGREZA GRAVE!')
    print('')
    print('//////'*18)
elif imc<17:
    print('//////'*18)
    print('')
    print('                                           MAGREZA MODERADA!')
    print('')
    print('//////'*18)
elif imc <18.5:
    print('//////'*18)
    print('')
    print('                                           MAGREZA  LEVE!')
    print('')
    print('//////'*18)
elif imc <25:
    print('//////'*18)
    print('')
    print('                                            SAUDÁVEL!')
    print('')
    print('//////'*18)
elif imc <30:
    print('//////'*18)
    print('')
    print('                                                SOBREPESO!')
    print('')
    print('//////'*18)
elif imc <35:
    print('//////'*18)
    print('')
    print('                                             OBESIDADE GRAU 1!')
    print('')
    print('//////'*18)
elif imc <40:
    print('//////'*18)
    print('')
    print('                                                 OBESIDADE GRAU 2 (SEVERA)!')
    print('')
    print('//////'*18)
else:
    print('//////'*18)
    print('')
    print('                                             OBESIDADE GRAU 3 (MÓRBIDA)!')
    print('')
    print('//////'*18)
input()
