from time import sleep
print('####'*24)
sleep(1)
print('                                   ESCOLA TESTE COMPUTACIONAL')
print('####'*24)
print('')
sleep(1)
nome=str(input('         Nome do aluno: '))
print('')
print('')
sleep(2)
print('####'*24)
print('                                      SELEÇÃO DE DISCIPLINA')
print('####'*24)
print('')
print('')
sleep (1)
disc1= 'LÍNGUA PORTUGUESA'
disc2='MATEMÁTICA'
disc3='GEOGRAFIA'
disc4='HISTÓRIA'
disc5='Ciências'
disc6='Inglês'
print('[ 1 ] Português')
print('[ 2 ] Matemática')
print('[ 3 ] Geografia')
print('[ 4 ] História')
print('[ 5 ] Ciências')
print('[ 5 ] Inglês')
print('')
materia=int(input('Selecione a matéria: '))
print('')
sleep(1)
if materia == 1:
    sleep(1)
    print('____'*24)
    print('')
    print('                           LANÇAMENTO DE NOTAS DE{}'. format(disc1))
    print('')
    print('____'*24)
elif materia ==2:
    sleep(1)
    print('')
    print('____'*24)
    print('')
    print('                            LANÇAMENTO DE NOTAS DE {}'. format(disc2))
    print('')
    print('____'*24)
elif materia==3:
    sleep(1)
    print('')
    print('____'*24)
    print('')
    print('                           LANÇAMENTO DE NOTAS DE {}'. format(disc3))
    print('')
    print('____'*24)
elif materia==4:
    sleep(1)
    print('')
    print('____'*24)
    print('')
    print('                           LANÇAMENTO DE NOTAS DE {}'. format(disc4))
    print('')
    print('____'*24)
elif materia==5:
    sleep(1)
    print('')
    print('____'*24)
    print('')
    print('                           LANÇAMENTO DE NOTAS DE {}'. format(disc5))
    print('')
    print('____'*24)
else:
    sleep(1)
    print('')
    print('____'*24)
    print('')
    print('                           LANÇAMENTO DE NOTAS DE {}'. format(disc6))
    print('')
    print('____'*24)
print('')
print('                 ¨¨¨¨¨¨¨¨ A SOMATÓRIA DAS NOTAS DEVEM TER UM TOTAL DE 100 PTS ¨¨¨¨¨¨¨')
sleep(1)
print('')
trab1=int(input('Trabalho 1 (Valor): '))
print('')
sleep(1)
trab2=int(input('Trabalho 2 (Valor): '))
print('')
sleep(1)
trab3=int(input('Trabalho 3 (Valor): '))
print('')
sleep(1)
Aval1=int(input('Avaliação 1 (Valor):  '))
print('')
sleep(1)
Aval2=int(input('Avaliação 2 (Valor): '))
print('')
soma=trab1+trab2+trab3+Aval1+Aval2
sleep(1)
print('                                   ANALISANDO AS NOTAS DO ALUNO...')
sleep(2)
print('____'*24)
print('')
print('                                   A NOTA FINAL DO ALUNO {} É {}'. format(nome, soma))
print('')
print('____'*24)
if soma <49:
    print('####'*24)
    print('')
    print('                                 ALUNO PERDEU MÉDIA ')
    print('')
    print('####'*24)
elif soma ==50:
    print('####'*24)
    print('')
    print('                                  ALUNO FICARÁ EM RECUPERAÇÃO')
    print('')
    print('####'*24)
elif soma>=60:
    print('####'*24)
    print('')
    print('                               ALUNO ATINGIU A MÉDIA\033[m')
    print('')
    print('####'*24)
input()
input()
    